[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.162.1"
  TZ = "UTC"

[context.production]
  command = "hugo --gc --minify"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture"
