# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Hugo - Deploy Organisation Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
   # - name: Checkout submodules using a PAT
   #   run: |
   #     git config --file .gitmodules --get-regexp url | while read url; do
   #       git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
   #     done
   #     git submodule sync
   #     git submodule update --init --recursive 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true 
    - name: build Hugo pages
      run: hugo --minify      
    - name: deploy generated pages
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.HUGO_DEPLOY_TOKENN }}
        # repository: smart-swimmingpool/smart-swimmingpool.github.io
        directory: public
     
